# Explore the different charts with Plotly Express

Plotly express is a must-have when it comes to static graphics.

In this introductory lecture about Plotly, we will cover:

* Display basic graphs with plotly.express
* Learn about the different types of charts

Before going deeper, let's have a look at the official documentation : https://plotly.com/python-api-reference/

In [1]:
import plotly.io as pio

# pio.renderers.default = "svg" # this line must be commented if working on colab

## First steps with plotly.express

Plotly Express is the high level API of plotly that will allow you to create basic graphs very easily.
### Downloading a dataset
The plotly.express has a `data` package that you can use to download light datasets that are very useful to make some tests (the full list of available datasets can be found [here](https://plotly.com/python-api-reference/generated/plotly.express.data.html))

In [2]:
import plotly.express as px
df = px.data.iris()
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

### First steps with plotly.express
To make a plot, you have to call the desired method, store the result in a variable (named `fig` in the example below), and call `fig.show()` to display it in your notebook :

In [3]:
fig = px.scatter(df, x = "sepal_width", y = "sepal_length")
fig.show()

Here is a list of the different types of figures you can create :

* [px.scatter](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)
* [px.scatter_3d ](https://plotly.com/python-api-reference/generated/plotly.express.scatter_3d.html)
* [px.scatter_polar](https://plotly.com/python-api-reference/generated/plotly.express.scatter_polar.html)
* [px.scatter_ternary](https://plotly.com/python-api-reference/generated/plotly.express.scatter_ternary.html)
* [px.scatter_mapbox](https://plotly.com/python-api-reference/generated/plotly.express.scatter_mapbox.html)
* [px.scatter_geo](https://plotly.com/python-api-reference/generated/plotly.express.scatter_geo.html)
* [px.line](https://plotly.com/python-api-reference/generated/plotly.express.line.html)
* [px.line_3d](https://plotly.com/python-api-reference/generated/plotly.express.line_3d.html)
* [px.line_polar](https://plotly.com/python-api-reference/generated/plotly.express.line_polar.html)
* [px.line_ternary](https://plotly.com/python-api-reference/generated/plotly.express.line_ternary.html)
* [px.line_mapbox](https://plotly.com/python-api-reference/generated/plotly.express.line_mapbox.html)
* [px.line_geo](https://plotly.com/python-api-reference/generated/plotly.express.line_geo.html)
* [px.area](https://plotly.com/python-api-reference/generated/plotly.express.area.html)
* [px.bar](https://plotly.com/python-api-reference/generated/plotly.express.bar.html)
* [px.bar_polar](https://plotly.com/python-api-reference/generated/plotly.express.bar_polar.html)
* [px.violin](https://plotly.com/python-api-reference/generated/plotly.express.violin.html)
* [px.box](https://plotly.com/python-api-reference/generated/plotly.express.box.html)
* [px.strip](https://plotly.com/python-api-reference/generated/plotly.express.strip.html)
* [px.histogram](https://plotly.com/python-api-reference/generated/plotly.express.histogram.html)
* [px.pie](https://plotly.com/python-api-reference/generated/plotly.express.pie.html)
* [px.treemap](https://plotly.com/python-api-reference/generated/plotly.express.treemap.html)
* [px.sunburst](https://plotly.com/python-api-reference/generated/plotly.express.sunburst.html)
* [px.funnel](https://plotly.com/python-api-reference/generated/plotly.express.funnel.html)
* [px.funnel_area](https://plotly.com/python-api-reference/generated/plotly.express.funnel_area.html)
* [px.scatter_matrix](https://plotly.com/python-api-reference/generated/plotly.express.scatter_matrix.html)
* [px.parallel_coordinates](https://plotly.com/python-api-reference/generated/plotly.express.parallel_coordinates.html)
* [px.parallel_categories](https://plotly.com/python-api-reference/generated/plotly.express.parallel_categories.html)
* [px.choropleth](https://plotly.com/python-api-reference/generated/plotly.express.choropleth.html)
* [px.choropleth_mapbox](https://plotly.com/python-api-reference/generated/plotly.express.choropleth_mapbox.html)
* [px.density_contour](https://plotly.com/python-api-reference/generated/plotly.express.density_contour.html)
* [px.density_heatmap](https://plotly.com/python-api-reference/generated/plotly.express.density_heatmap.html)
* [px.density_mapbox](https://plotly.com/python-api-reference/generated/plotly.express.density_mapbox.html)
* [px.imshow](https://plotly.com/python-api-reference/generated/plotly.express.imshow.html)


### Using plotly.express methods' arguments to refine the figures

As in seaborn, the methods listed above have a bunch of optional arguments that allow to add some information to the figures. Depending on the method you are using, the available options can be different. Please refer to the documentation to know which options are available for a given method. Let's go through some examples with the `px.scatter` method :

#### Color

You can change the marker color depending on a given categorical column of your dataset :

In [4]:
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species")
fig.show()

#### Changing the colorscale
You can change the color scale, by using either a discrete color sequence or a continuous colorscale. There are plenty of built-in colorscales available in Plotly.

You can refer to these documentation pages:
* [Discrete colors in Plotly](https://plotly.com/python/discrete-color/)
* [Continuous colorscales](https://plotly.com/python/colorscales/)
* [Built-in continuous colorscales](https://plotly.com/python/builtin-colorscales/)

In [5]:
# Discrete sequence
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species",
                 color_discrete_sequence = px.colors.qualitative.Pastel)
fig.show()

In [6]:
# Continuous sequence - column passed in "color" must be numeric
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species_id",
                 color_continuous_scale = px.colors.sequential.Plasma)
fig.show()

#### Trendline
You can add a trendline as in the following :

In [14]:
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species", trendline = "expanding")
fig.show()

#### 3D visualisation
There's also a `scatter_3d` method that allows you to add one more dimension to your visualisation :

In [15]:
fig = px.scatter_3d(df, x = "sepal_width", y = "sepal_length", z = "petal_length", color = "species")
fig.show()

#### Marginals
Let's go back to the 2D scatter plot. You can add some summarized information by using the `marginal_x` and `marginal_y` arguments :

In [17]:
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species", trendline = "expanding", marginal_x = "violin", marginal_y = "box")
fig.show()

#### Facets
You can use `facet_row` and `facet_col` to create some facets, each containing the data for a given category. If you're using it together with the `marginal_x` and `marginal_y` options, the marginals won't be displayed :

In [18]:
# Create one subgraph for each category and set the dislay order
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species", trendline = "expanding", marginal_x = "violin", marginal_y = "box",
                 facet_row = "species")
fig.show()

In [19]:
# Create one subgraph for each category and set the dislay order
fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species", trendline = "expanding", marginal_x = "violin", marginal_y = "box",
                 facet_row = "species", facet_col = "species_id")
fig.show()

#### Categories order
Finally, you can change the order of the categories that you are using with the facets thanks to `category_orders` :

In [21]:
category_orders_dict = {
    "species" : ["setosa", "virginica", "versicolor"],
    "species_id" : [3, 2, 1]
}

fig = px.scatter(df, x = "sepal_width", y = "sepal_length", color = "species", trendline = "expanding", marginal_x = "violin",
                 marginal_y = "box", facet_row = "species", facet_col = "species_id", category_orders = category_orders_dict)
fig.show()

## The different types of charts

Now that you've become familiar with Plotly Express, let's explore the main different types of charts and their applications.

### Scatter plots
All the examples above were illustrating a scatter plot.

Scatter plots are best for displaying values for two variables from a dataset. They are great for **showing the overall relationship between the two variables** in a large amount of data.

The data is displayed as a collection of points; the value of one variable determines the position on the horizontal axis, while the value of the other variable determines the position on the vertical axis.

### Line plots
Line charts are best used when trying to visualize **numeric data over time**. Line charts are set against a common scale and are ideal for showing trends in data.

In [22]:
df = px.data.gapminder()
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [23]:
# Create df for France
df_france = df.loc[df['country']== "France", :]

In [24]:
fig = px.line(df_france, x = "year", y = "lifeExp")
fig.show()

In [25]:
# Create df for Oceania
df_oceania = df.loc[df['continent']== "Oceania", :]

In [26]:
# Remember there exists lots of extra arguments you can use to refine your plot
fig = px.line(df_oceania, x = "year", y = "lifeExp", color="country")
fig.show()

## Histograms
Histograms are appropriate to show the **distribution of a numeric variable**.
An important parameter is the number of bins, which will define the "level of details":
* For small datasets, the number of bins must be small
* For bigger datasets, the number of bins can be higher

In [27]:
df = px.data.tips()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
fig = px.histogram(df, x = "tip")
fig.show()

In [29]:
# Number of bins to low
fig = px.histogram(df, x = "tip", nbins = 5)
fig.show()

In [30]:
# Number of bins to high
fig = px.histogram(df, x = "tip", nbins = 500)
fig.show()

## Bar charts
Bar charts are best used when showing **comparisons between categories**. Typically, the bars are proportional to the values they represent and can be plotted either horizontally or vertically. One axis of the chart shows the specific categories being compared, and the other axis represents numeric values. Bar charts are ideal when you’re working with limited space.

In [31]:
# Average bill grouped by day
df_day = df.groupby('day')['total_bill'].mean().reset_index()
df_day.head()

    day  total_bill
0   Fri   17.151579
1   Sat   20.441379
2   Sun   21.410000
3  Thur   17.682742

In [32]:
fig = px.bar(df_day, x = "day", y = "total_bill")
fig.show()

In [33]:
# Average bill grouped by day and time
df_day_time = df.groupby(['day','time'])['total_bill'].mean().reset_index()
df_day_time.head()

    day    time  total_bill
0   Fri  Dinner   19.663333
1   Fri   Lunch   12.845714
2   Sat  Dinner   20.441379
3   Sun  Dinner   21.410000
4  Thur  Dinner   18.780000

In [34]:
# px.bar will stack bars by default
fig = px.bar(df_day_time, x = "day", y = "total_bill", color = "time")
fig.show()

In [35]:
# You can use the barmode argument to change this behaviour
fig = px.bar(df_day_time, x = "day", y = "total_bill", color = "time", barmode = "group")
fig.show()

In [36]:
# Change the orientation of the bars - you must swap x and y !
fig = px.bar(df_day_time, x = "total_bill", y = "day", color = "time",
             barmode = "group", orientation = "h")
fig.show()

## Boxplots
Whisker Charts or Box Plots are very useful to **compare distributions of numeric variables across different categories**.

In [37]:
fig = px.box(df, x = 'day', y = 'total_bill', color = 'time')
fig.show()

## Pie charts
Pie charts are best used to compare parts to the whole. Pie charts make it easy for an audience to understand the relative importance of values, but when there are more than five sections, it can become difficult to compare the results. The difference between the sections can become too narrow to effectively interpret.

In [38]:
# Compute total revenue cumulated by day
df_revenue = df.groupby('day')['total_bill'].sum().reset_index()
df_revenue.head()

    day  total_bill
0   Fri      325.88
1   Sat     1778.40
2   Sun     1627.16
3  Thur     1096.33

In [39]:
fig = px.pie(df_revenue, names = "day", values = "total_bill")
fig.show()

## Bubble charts
Bubble Charts are used to show **three dimensions of data—comparing entities** in terms of their relative values, positions, and sizes. Bubble charts are similar to scatter plots, where the data points are replaced with bubbles.

In [40]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [41]:
# To create a bubble chart, just use the argument size of the px.scatter function
fig = px.scatter(df, x = "total_bill", y = "tip", size = "size", color = "smoker")
fig.show()

## Geographical data
If the dataset contains information about latitude and longitude, you can use px.scatter_mapbox to display the data on a map!

In [42]:
df_car = px.data.carshare()
df_car.head()

   centroid_lat  centroid_lon    car_hours  peak_hour
0     45.471549    -73.588684  1772.750000          2
1     45.543865    -73.562456   986.333333         23
2     45.487640    -73.642767   354.750000         20
3     45.522870    -73.595677   560.166667         23
4     45.453971    -73.738946  2836.666667         19

In [43]:
fig = px.scatter_mapbox(df_car, lat="centroid_lat", lon="centroid_lon", color="peak_hour", size="car_hours",
                        zoom=10, mapbox_style="carto-positron")
fig.show()

C:\Users\NLefort\AppData\Local\Temp\ipykernel_8552\210935699.py:1: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

### Making awesome animations
Last but not least : it's possible to create animated graphs with Plotly ! You just need to set the animation_frame and (optionnaly) animation_group arguments:

In [44]:
df = px.data.gapminder()
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [45]:
fig = px.scatter(df, x = "gdpPercap", y = "lifeExp", animation_frame = "year", animation_group = "country",
                    size = "pop", color = "continent", hover_name = "country",
                    log_x = True, size_max = 55, range_x = [100,100000], range_y = [25,90])

fig.show()

# Saving figures with plotly.io
Once you're satisfied with some figures that you would like to save into files for later use, you can use plotly.io.

In [46]:
import plotly.io as pio

pio.write_html(fig, "figure.html")

## Resources 📚📚
* [Plotly Express](https://plotly.com/python/plotly-express/)
* [Discrete colors in Plotly](https://plotly.com/python/discrete-color/)
* [Continuous colorscales](https://plotly.com/python/colorscales/)
* [Built-in continuous colorscales](https://plotly.com/python/builtin-colorscales/)
* [Intro to Animations in Python](https://plotly.com/python/animations/)